
* topic describe someone in your family who you like
hello  
Philippine

* topic describe a famous person
** one
*** who:
The person I would to meet is curry. I very enjoy all match he played.
*** what
he/she does: curry is a famous NBA player in the United States. he can shot 3-point
anywhere in court.
*** why he/she is famous:
he become more and more popular. 
*** why you want to meet him/her:

* topic describe a friend of your family you remember from your childhood.
** one
*** who the person was
The friend of my family that I remember from my childhood is Lju.

*** how your family knew this person
Liu has been our neighbor since i was three. we lived door to door.
we knew him through his father, his father is my father's colleague.

*** how often this person visited your family and explain
Liu is 2 years older than me and we went to the same elementary school.
Liu used to visit our family after school.

*** why you remember this person
I remember Liu very well because we spent lots of time playing together.
He just like my big brother.

* topic describe a persion who done a lot of work to help people
** one
*** who this person is/was
today i wanna say the person who helps people a lot is a pedicab dirver
who helped 300 of students. he died in 2005. he is great man.
*** where this person lives/lived
bai lived in tianjin. the city where i was born.
*** what he/she has done to help people
i learned about bai through news on the internet. he work at hight age
around 90 years. all the money he earned is donated to school for students
who can not afford tuition
*** and explain how you know about him/her
bai helped 300 students finish their studies. he live so tough just for
helping other people. i remember the words he said when he last time donate
"this is my last time donate. i am too old and i cant ride pedicab anymore
